version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
      - run: 'docker pull jetbrains/qodana-jvm-community'
      - run: 'docker run --rm -it -p 8080:8080 -v $(pwd)/:/data/project/ -v $(pwd)/:/data/results/ jetbrains/qodana-jvm-community --save-report'