version: 2.1
jobs:
  build:
    docker:
      - image: jetbrains/qodana-jvm-community
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: docker pull jetbrains/qodana-jvm-community
      - run: docker run --rm -it -p 8080:8080 -v $(pwd)/:/data/project/ -v $(pwd)/:/data/results/ jetbrains/qodana-jvm-community --show-report