version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 'echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin'
      - run: 'docker pull jetbrains/qodana-jvm-community'
      - run: 'docker run --rm -it -p 8080:8080 -v $(pwd)/:/data/project/ -v $(pwd)/:/data/results/ jetbrains/qodana-jvm-community --save-report > result.txt'
      - run: |
          if grep 'problems detected' result.txt ;
            then exit 1
          fi