version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull jetbrains/qodana-jvm-community
      - run: docker run --rm -it -p 8080:8080 -v $(pwd)/:/data/project/ -v $(pwd)/:/data/results/ jetbrains/qodana-jvm-community --show-report