name: Qodana check on pull requests
on: [pull_request]
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JetBrains/qodana-action@v3.2.1
        with:
          linter: qodana-jvm-community
          fail-threshold: 1
